In [2]:
import fastf1
from fastf1 import Cache

Cache.enable_cache('cache')
Cache.enable_cache(
    cache_dir='cache',
    ignore_version=False,
    force_renew=False,
    use_requests_cache=True
)
schedule = fastf1.get_event_schedule(2025)
schedule = schedule[['RoundNumber', 'EventDate', 'EventName']]
print(schedule)

    RoundNumber  EventDate                  EventName
0             0 2025-02-28         Pre-Season Testing
1             1 2025-03-16      Australian Grand Prix
2             2 2025-03-23         Chinese Grand Prix
3             3 2025-04-06        Japanese Grand Prix
4             4 2025-04-13         Bahrain Grand Prix
5             5 2025-04-20   Saudi Arabian Grand Prix
6             6 2025-05-04           Miami Grand Prix
7             7 2025-05-18  Emilia Romagna Grand Prix
8             8 2025-05-25          Monaco Grand Prix
9             9 2025-06-01         Spanish Grand Prix
10           10 2025-06-15        Canadian Grand Prix
11           11 2025-06-29        Austrian Grand Prix
12           12 2025-07-06         British Grand Prix
13           13 2025-07-27         Belgian Grand Prix
14           14 2025-08-03       Hungarian Grand Prix
15           15 2025-08-31           Dutch Grand Prix
16           16 2025-09-07         Italian Grand Prix
17           17 2025-09-21      Azerbaijan Grand Prix
18           18 2025-10-05       Singapore Grand Prix
19           19 2025-10-19   United States Grand Prix
20           20 2025-10-26     Mexico City Grand Prix
21           21 2025-11-09       São Paulo Grand Prix
22           22 2025-11-22       Las Vegas Grand Prix
23           23 2025-11-30           Qatar Grand Prix
24           24 2025-12-07       Abu Dhabi Grand Prix

In [3]:
import pandas as pd
import numpy as np


def build_season(year):
    schedule = fastf1.get_event_schedule(year)
    schedule = schedule[schedule['RoundNumber'] > 0]  

    season_rows = []
    for rnd in schedule['RoundNumber']:
        rnd = int(rnd)
        event_name = schedule.loc[schedule['RoundNumber'] == rnd, 'EventName'].values[0]
        try:
            session = fastf1.get_session(year, rnd, 'R')
            qual = fastf1.get_session(year, rnd, 'Q')
            session.load(laps=True, weather=True)
            qual.load(laps=True, weather=True)
        except Exception as e:
            print(f"Skipping {year} round {rnd} ({event_name}): {e}")
            continue

        # Race results already carry starting grid + finishing position
        df = session.results.copy()
        df['Year'] = year
        df['Round'] = rnd
        df['EventName'] = event_name
        df = df.rename(columns={
            'GridPosition': 'StartingGridPosition',
            'Position': 'FinishingPosition',
        })

        # --- Lap time per driver (seconds) ---
        laps = session.laps
        if laps is not None and not laps.empty:
            lap_agg = laps.groupby('Driver')['LapTime'].agg(
                AvgLapTime='mean',
                MedianLapTime='median',
                FastestLapTime='min',
            ).reset_index()
            for col in ['AvgLapTime', 'MedianLapTime', 'FastestLapTime']:
                lap_agg[col] = lap_agg[col].dt.total_seconds()
            df = df.merge(lap_agg, left_on='Abbreviation', right_on='Driver', how='left')
            df = df.drop(columns=['Driver'])

        # --- Weather (session-level; same value for every driver at this track) ---
        weather = session.weather_data
        if weather is not None and not weather.empty:
            df['AirTemp'] = weather['AirTemp'].mean()
            df['TrackTemp'] = weather['TrackTemp'].mean()
            df['Humidity'] = weather['Humidity'].mean()
            df['Pressure'] = weather['Pressure'].mean()
            df['WindSpeed'] = weather['WindSpeed'].mean()
            df['Rainfall'] = bool(weather['Rainfall'].any())


        if qual is not None and not qual.results.empty:
            q = qual.results[['Abbreviation', 'Position', 'Q1', 'Q2', 'Q3']].copy()
            for c in ['Q1', 'Q2', 'Q3']:
                q[c] = q[c].dt.total_seconds()

            best = q[['Q1', 'Q2', 'Q3']].min(axis=1)          # NaT segments collapse away
            q['KnockedOutIn'] = np.where(q['Q3'].notna(), 'Q3',
                                np.where(q['Q2'].notna(), 'Q2', 'Q1'))
            q.loc[best.isna(), 'KnockedOutIn'] = 'NoTime'
            q['QualNoTime'] = best.isna().astype(float)

            gap = 100 * (best - best.min()) / best.min()       # race-relative, not raw seconds
            q['QualGapToPolePct'] = gap.fillna(gap.max() + 1.0)   # no lap -> worse than slowest
            q['QualPosition'] = q['Position'].fillna(20.0)

            df = df.merge(q[['Abbreviation', 'QualPosition', 'QualGapToPolePct',
                             'KnockedOutIn', 'QualNoTime']],
                          on='Abbreviation', how='left', validate='one_to_one')

        season_rows.append(df)

    season_df = pd.concat(season_rows, ignore_index=True)

    keep = [
        'Year', 'Round', 'EventName',
        'Abbreviation', 'DriverNumber', 'TeamName',
        'StartingGridPosition', 'FinishingPosition', 
        'QualPosition', 'QualGapToPolePct', 'KnockedOutIn', 'QualNoTime',
        'AvgLapTime', 'MedianLapTime', 'FastestLapTime',
        'AirTemp', 'TrackTemp', 'Humidity', 'Pressure', 'WindSpeed', 'Rainfall',
    ]
    keep = [c for c in keep if c in season_df.columns]
    return season_df[keep]

In [4]:
# Build 2024: weather, lap time, starting grid + finishing position per driver per track
results_2024_df = build_season(2024)
print(results_2024_df.shape)
results_2024_df.head(20)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '14', '81', '4', '63', '44', '22', '18', '38', '23', '20', '3', '27', '77', '31', '10', '2', '24']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['1', '55', '11', '4', '16', '81', '63', '22', '18', '14', '44', '23', '77', '20', '31', '27', '10', '3', '24']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '55', '14', '81', '44', '16', '63', '22', '3', '27', '77', '23', '31', '18', '10', '20', '2', '24']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '4', '81', '16', '55', '63', '27', '77', '18', '3', '31', '23', '10', '24', '20', '44', '22', '2']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '4', '81', '63', '44', '27', '22', '18', '10', '31', '23', '14', '77', '2', '3', '20', '24']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '55', '63', '22', '44', '3', '27', '11', '31', '18', '23', '10', '77', '24', '20', '14', '2']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '31', '3', '18', '27', '14', '2', '20', '11', '77', '24']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']
core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '3', '14', '44', '22', '18', '23', '16', '55', '2', '20', '10', '11', '77', '31', '27', '24']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']
core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '16', '55', '10', '11', '31', '81', '14', '77', '27', '18', '24', '20', '22', '3', '23', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']
core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

(479, 21)

,Year,Round,EventName,Abbreviation,DriverNumber,TeamName,StartingGridPosition,FinishingPosition,QualPosition,QualGapToPolePct,...,QualNoTime,AvgLapTime,MedianLapTime,FastestLapTime,AirTemp,TrackTemp,Humidity,Pressure,WindSpeed,Rainfall
0,2024,1,Bahrain Grand Prix,VER,1,Red Bull Racing,1.0,1.0,1.0,0.015701,...,0.0,96.574421,95.6790,92.608,18.227389,23.652866,48.821656,1017.185987,0.785987,False
1,2024,1,Bahrain Grand Prix,PER,11,Red Bull Racing,5.0,2.0,5.0,0.417204,...,0.0,96.968404,96.2490,94.364,18.227389,23.652866,48.821656,1017.185987,0.785987,False
2,2024,1,Bahrain Grand Prix,SAI,55,Ferrari,4.0,3.0,4.0,0.383559,...,0.0,97.014947,96.2200,94.507,18.227389,23.652866,48.821656,1017.185987,0.785987,False
3,2024,1,Bahrain Grand Prix,LEC,16,Ferrari,2.0,4.0,2.0,0.000000,...,0.0,97.270368,96.7960,94.090,18.227389,23.652866,48.821656,1017.185987,0.785987,False
4,2024,1,Bahrain Grand Prix,RUS,63,Mercedes,3.0,5.0,3.0,0.358885,...,0.0,97.395263,96.6830,95.065,18.227389,23.652866,48.821656,1017.185987,0.785987,False
5,2024,1,Bahrain Grand Prix,NOR,4,McLaren,7.0,6.0,7.0,0.503561,...,0.0,97.424561,96.6200,94.476,18.227389,23.652866,48.821656,1017.185987,0.785987,False
6,2024,1,Bahrain Grand Prix,HAM,44,Mercedes,9.0,7.0,9.0,0.611226,...,0.0,97.457298,96.6940,94.722,18.227389,23.652866,48.821656,1017.185987,0.785987,False
7,2024,1,Bahrain Grand Prix,PIA,81,McLaren,8.0,8.0,8.0,0.580945,...,0.0,97.558316,96.7960,94.774,18.227389,23.652866,48.821656,1017.185987,0.785987,False
8,2024,1,Bahrain Grand Prix,ALO,14,Aston Martin,6.0,9.0,6.0,0.422812,...,0.0,97.888228,97.2650,94.199,18.227389,23.652866,48.821656,1017.185987,0.785987,False
9,2024,1,Bahrain Grand Prix,STR,18,Aston Martin,12.0,10.0,12.0,0.897213,...,0.0,98.209789,97.1750,95.632,18.227389,23.652866,48.821656,1017.185987,0.785987,False
10,2024,1,Bahrain Grand Prix,ZHO,24,Kick Sauber,17.0,11.0,17.0,1.785454,...,0.0,98.419661,97.4590,95.458,18.227389,23.652866,48.821656,1017.185987,0.785987,False
11,2024,1,Bahrain Grand Prix,MAG,20,Haas F1 Team,15.0,12.0,15.0,1.529748,...,0.0,98.447464,97.9470,95.570,18.227389,23.652866,48.821656,1017.185987,0.785987,False
12,2024,1,Bahrain Grand Prix,RIC,3,RB,14.0,13.0,14.0,1.248248,...,0.0,98.458929,97.8185,95.163,18.227389,23.652866,48.821656,1017.185987,0.785987,False
13,2024,1,Bahrain Grand Prix,TSU,22,RB,11.0,14.0,11.0,1.081142,...,0.0,98.468286,97.6885,95.833,18.227389,23.652866,48.821656,1017.185987,0.785987,False
14,2024,1,Bahrain Grand Prix,ALB,23,Williams,13.0,15.0,13.0,1.184321,...,0.0,98.511214,97.9430,95.723,18.227389,23.652866,48.821656,1017.185987,0.785987,False
15,2024,1,Bahrain Grand Prix,HUL,27,Haas F1 Team,10.0,16.0,10.0,0.769360,...,0.0,98.613821,96.9470,94.834,18.227389,23.652866,48.821656,1017.185987,0.785987,False
16,2024,1,Bahrain Grand Prix,OCO,31,Alpine,19.0,17.0,19.0,1.825829,...,0.0,98.860571,98.0845,96.226,18.227389,23.652866,48.821656,1017.185987,0.785987,False
17,2024,1,Bahrain Grand Prix,GAS,10,Alpine,20.0,18.0,20.0,1.999664,...,0.0,98.877839,97.9085,94.805,18.227389,23.652866,48.821656,1017.185987,0.785987,False
18,2024,1,Bahrain Grand Prix,BOT,77,Kick Sauber,16.0,19.0,16.0,1.784332,...,0.0,98.503745,97.8460,96.202,18.227389,23.652866,48.821656,1017.185987,0.785987,False
19,2024,1,Bahrain Grand Prix,SAR,2,Williams,18.0,20.0,18.0,1.800034,...,0.0,99.327352,97.7420,94.735,18.227389,23.652866,48.821656,1017.185987,0.785987,False

In [5]:
# Build 2025: weather, lap time, starting grid + finishing position per driver per track
results_2025_df = build_season(2025)
print(results_2025_df.shape)
results_2025_df.head(20)

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
Request for URL https://api.jolpi.ca/ergast/f1/2025/3/qualifying.json failed; using cached response
Traceback (most recent call last):
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connection.py", line 571, in getresponse
    httplib_response = super().getresponse()
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/requests/adapters.py", line 696, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connectionpool.py", line 842, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/util/retry.py", line 498, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.jolpi.ca', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/requests_cache/session.py", line 311, in _resend
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/requests_cache/session.py", line 279, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/fastf1/req.py", line 112, in send
    return super().send(request, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/requests/sessions.py", line 784, in send
    r = adapter.send(request, **kwargs)
  File "/Users/PaulAbruzzo/Documents/f1_prediction_model/f1-env/lib/python3.13/site-packages/requests/adapters.py", line 742, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.jolpi.ca', port=443): Read timed out. (read timeout=5.0)
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '63', '16', '12', '55', '44', '22', '10', '4', '23', '30', '14', '6', '87', '18', '7', '27', '31', '5']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '12', '81', '63', '55', '23', '16', '31', '22', '6', '44', '5', '7', '30', '27', '14', '10', '18', '87']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '63', '4', '14', '55', '23', '18', '6', '10', '16', '44', '12', '5', '43', '30', '87', '27', '31', '22']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']
core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

(479, 21)

,Year,Round,EventName,Abbreviation,DriverNumber,TeamName,StartingGridPosition,FinishingPosition,QualPosition,QualGapToPolePct,...,QualNoTime,AvgLapTime,MedianLapTime,FastestLapTime,AirTemp,TrackTemp,Humidity,Pressure,WindSpeed,Rainfall
0,2025,1,Australian Grand Prix,NOR,4,McLaren,1.0,1.0,1.0,0.000000,...,0.0,103.428302,90.551,82.167,15.707865,18.942135,78.421348,1009.901685,3.475281,True
1,2025,1,Australian Grand Prix,VER,1,Red Bull Racing,3.0,2.0,3.0,0.512677,...,0.0,103.341151,91.271,83.081,15.707865,18.942135,78.421348,1009.901685,3.475281,True
2,2025,1,Australian Grand Prix,RUS,63,Mercedes,4.0,3.0,4.0,0.599233,...,0.0,103.686340,91.856,85.065,15.707865,18.942135,78.421348,1009.901685,3.475281,True
3,2025,1,Australian Grand Prix,ANT,12,Mercedes,16.0,4.0,16.0,1.902898,...,0.0,104.579370,93.697,84.901,15.707865,18.942135,78.421348,1009.901685,3.475281,True
4,2025,1,Australian Grand Prix,ALB,23,Williams,6.0,5.0,6.0,0.853574,...,0.0,104.672389,93.051,84.597,15.707865,18.942135,78.421348,1009.901685,3.475281,True
5,2025,1,Australian Grand Prix,STR,18,Aston Martin,13.0,6.0,13.0,1.695164,...,0.0,104.730130,93.631,85.538,15.707865,18.942135,78.421348,1009.901685,3.475281,True
6,2025,1,Australian Grand Prix,HUL,27,Kick Sauber,17.0,7.0,17.0,1.974806,...,0.0,104.740167,94.064,85.243,15.707865,18.942135,78.421348,1009.901685,3.475281,True
7,2025,1,Australian Grand Prix,LEC,16,Ferrari,7.0,8.0,7.0,0.877543,...,0.0,103.933528,92.448,85.271,15.707865,18.942135,78.421348,1009.901685,3.475281,True
8,2025,1,Australian Grand Prix,PIA,81,McLaren,2.0,9.0,2.0,0.111857,...,0.0,102.084462,90.722,83.242,15.707865,18.942135,78.421348,1009.901685,3.475281,True
9,2025,1,Australian Grand Prix,HAM,44,Ferrari,8.0,10.0,8.0,1.095931,...,0.0,103.967189,92.914,84.218,15.707865,18.942135,78.421348,1009.901685,3.475281,True
10,2025,1,Australian Grand Prix,GAS,10,Alpine,9.0,11.0,9.0,1.177160,...,0.0,104.889167,92.969,85.020,15.707865,18.942135,78.421348,1009.901685,3.475281,True
11,2025,1,Australian Grand Prix,TSU,22,Racing Bulls,5.0,12.0,5.0,0.764355,...,0.0,104.085698,92.762,84.194,15.707865,18.942135,78.421348,1009.901685,3.475281,True
12,2025,1,Australian Grand Prix,OCO,31,Haas F1 Team,19.0,13.0,19.0,2.731171,...,0.0,103.848698,94.392,86.764,15.707865,18.942135,78.421348,1009.901685,3.475281,True
13,2025,1,Australian Grand Prix,BEA,87,Haas F1 Team,20.0,14.0,20.0,3.731171,...,1.0,103.870075,94.094,87.603,15.707865,18.942135,78.421348,1009.901685,3.475281,True
14,2025,1,Australian Grand Prix,LAW,30,Red Bull Racing,18.0,15.0,18.0,2.660594,...,0.0,101.752524,93.617,82.970,15.707865,18.942135,78.421348,1009.901685,3.475281,True
15,2025,1,Australian Grand Prix,BOR,5,Kick Sauber,15.0,16.0,15.0,1.890913,...,0.0,102.655634,93.792,84.192,15.707865,18.942135,78.421348,1009.901685,3.475281,True
16,2025,1,Australian Grand Prix,ALO,14,Aston Martin,12.0,17.0,12.0,1.587302,...,0.0,98.517379,92.521,88.819,15.707865,18.942135,78.421348,1009.901685,3.475281,True
17,2025,1,Australian Grand Prix,SAI,55,Williams,10.0,18.0,10.0,1.111910,...,0.0,NaN,NaN,NaN,15.707865,18.942135,78.421348,1009.901685,3.475281,True
18,2025,1,Australian Grand Prix,DOO,7,Alpine,14.0,19.0,14.0,1.623256,...,0.0,NaN,NaN,NaN,15.707865,18.942135,78.421348,1009.901685,3.475281,True
19,2025,1,Australian Grand Prix,HAD,6,Racing Bulls,11.0,20.0,11.0,1.436828,...,0.0,NaN,NaN,NaN,15.707865,18.942135,78.421348,1009.901685,3.475281,True

In [6]:
import openpyxl as xl
results_2024_df.to_excel('f1_2024_results.xlsx', index=False)
results_2025_df.to_excel('f1_2025_results.xlsx', index=False)

In [7]:
qual = fastf1.get_session(2025, 1, 'Q')
qual.load(laps=True, weather=True)
display(qual.results.head(20))

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
4,4,L NORRIS,NOR,norris,McLaren,FF8000,mclaren,Lando,Norris,Lando Norris,...,1.0,,NaN,0 days 00:01:15.912000,0 days 00:01:15.415000,0 days 00:01:15.096000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,FF8000,mclaren,Oscar,Piastri,Oscar Piastri,...,2.0,,NaN,0 days 00:01:16.062000,0 days 00:01:15.468000,0 days 00:01:15.180000,NaT,,NaN,NaN
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,3.0,,NaN,0 days 00:01:16.018000,0 days 00:01:15.565000,0 days 00:01:15.481000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,4.0,,NaN,0 days 00:01:15.971000,0 days 00:01:15.798000,0 days 00:01:15.546000,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6692FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,5.0,,NaN,0 days 00:01:16.225000,0 days 00:01:16.009000,0 days 00:01:15.670000,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,64C4FF,williams,Alexander,Albon,Alexander Albon,...,6.0,,NaN,0 days 00:01:16.245000,0 days 00:01:16.017000,0 days 00:01:15.737000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,7.0,,NaN,0 days 00:01:16.029000,0 days 00:01:15.827000,0 days 00:01:15.755000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,E80020,ferrari,Lewis,Hamilton,Lewis Hamilton,...,8.0,,NaN,0 days 00:01:16.213000,0 days 00:01:15.919000,0 days 00:01:15.973000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,...,9.0,,NaN,0 days 00:01:16.328000,0 days 00:01:16.112000,0 days 00:01:15.980000,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,64C4FF,williams,Carlos,Sainz,Carlos Sainz,...,10.0,,NaN,0 days 00:01:16.360000,0 days 00:01:15.931000,0 days 00:01:16.062000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Racing Bulls,6692FF,rb,Isack,Hadjar,Isack Hadjar,...,11.0,,NaN,0 days 00:01:16.354000,0 days 00:01:16.175000,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,12.0,,NaN,0 days 00:01:16.288000,0 days 00:01:16.453000,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,13.0,,NaN,0 days 00:01:16.369000,0 days 00:01:16.483000,NaT,NaT,,NaN,NaN
7,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,...,14.0,,NaN,0 days 00:01:16.315000,0 days 00:01:16.863000,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Kick Sauber,52E252,sauber,Gabriel,Bortoleto,Gabriel Bortoleto,...,15.0,,NaN,0 days 00:01:16.516000,0 days 00:01:17.520000,NaT,NaT,,NaN,NaN
12,12,A ANTONELLI,ANT,antonelli,Mercedes,27F4D2,mercedes,Andrea Kimi,Antonelli,Andrea Kimi Antonelli,...,16.0,,NaN,0 days 00:01:16.525000,NaT,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Kick Sauber,52E252,sauber,Nico,Hulkenberg,Nico Hulkenberg,...,17.0,,NaN,0 days 00:01:16.579000,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Red Bull Racing,3671C6,red_bull,Liam,Lawson,Liam Lawson,...,18.0,,NaN,0 days 00:01:17.094000,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,B6BABD,haas,Esteban,Ocon,Esteban Ocon,...,19.0,,NaN,0 days 00:01:17.147000,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,B6BABD,haas,Oliver,Bearman,Oliver Bearman,...,20.0,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN

In [8]:
from sklearn.feature_extraction import DictVectorizer
#now we have all the data we need from the results df. Lets use this to build a vector of features we will train our model on

#lets get an array, where each entry is a dict of our data that we will train on.
#for each race, we want weather, starting grid, finishing grid, track, laptime, driver, team, and year. We can add more in the future
CATEGORICAL = ['EventName', 'Abbreviation', 'TeamName', 'Year', 'KnockedOutIn']
NUMERIC = ['StartingGridPosition', 'QualPosition', 'QualGapToPolePct', 'QualNoTime',
'AvgLapTime', 'MedianLapTime', 'FastestLapTime',
           'AirTemp', 'TrackTemp', 'Humidity', 'Pressure', 'WindSpeed', 'Rainfall']
TARGET = 'FinishingPosition'

def to_records(df):
    out = df.copy()
    for c in CATEGORICAL:
        out[c] = out[c].astype(str)
    for c in NUMERIC:
        out[c] = out[c].astype(float)
    
    records = [
        {k: v for k, v in row.items() if not (isinstance(v, float) and np.isnan(v))}  # drop NaN values
        for row in out[CATEGORICAL + NUMERIC].to_dict(orient='records')
    ]
    y = df[TARGET].to_numpy() if TARGET in df else None
    return records, y

features, Y = to_records(results_2024_df)
vector = DictVectorizer()
X = vector.fit_transform(features).toarray()

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import mean_absolute_error
from scipy.stats import spearmanr

df = results_2024_df.sort_values('Round').reset_index(drop=True)

train_df = df[df.Round <= 19]
test_df  = df[df.Round > 19]

feat_train, y_train = to_records(train_df)
feat_test,  y_test  = to_records(test_df)

vector = DictVectorizer(sparse=False)
X_train = vector.fit_transform(feat_train)   # fit on train only
X_test  = vector.transform(feat_test)        # transform, never fit

model = GradientBoostingRegressor(random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)



mae = mean_absolute_error(y_test, pred)
scored = test_df.assign(pred=pred)
rho = np.mean([spearmanr(g[TARGET], g['pred']).statistic
               for _, g in scored.groupby('Round')])

In [ ]:
print(f"feats={X_train.shape[1]}  MAE={mae:.2f}  rho={rho:+.3f}")

scored['PredictedFinish'] = (scored.groupby('Round')['pred']
                                   .rank(method='first').astype(int))

out = (scored.sort_values(['Round', 'FinishingPosition'])
             [['Round', 'EventName', 'Abbreviation', 'StartingGridPosition',
               'FinishingPosition', 'PredictedFinish', 'pred']]
             .rename(columns={'EventName': 'Track', 'Abbreviation': 'Driver',
                              'StartingGridPosition': 'Grid',
                              'FinishingPosition': 'Actual',
                              'PredictedFinish': 'Predicted',
                              'pred': 'RawScore'}))

out['Error'] = out['Predicted'] - out['Actual']

out.to_excel('predictions_2024.xlsx', index=False)

feats=70  MAE=3.21  rho=+0.697